---
- hosts: all
  become: yes

  tasks:

    - name: install Apache
      yum: name=httpd  state=present

    - name: enable apache from start
      command: systemctl enable httpd.service

    - name: start httpd daemon
      command: systemctl start httpd.service
    

    - name: Determine if firewalld service masked
      command: systemctl is-enabled firewalld
      register: os_firewall_firewalld_masked_output
      changed_when: false
      failed_when: false

    - name: Unmask firewalld service
      command: systemctl unmask firewalld
      when: os_firewall_firewalld_masked_output.stdout == "masked"

    - name: Start and enable firewalld service
      service:
        name: firewalld
        state: restarted
        enabled: yes
      register: result

